{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "backend.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: istio-ingress
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | default "*" | quote }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "backend.fullname" . }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.host | default "*" | quote }}
  gateways:
    - {{ include "backend.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "backend.fullname" . }}
            port:
              number: 80
{{- end }}
