apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "backend.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | quote }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "backend.fullname" . }}-vs
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - {{ include "backend.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "backend.fullname" . }}
            port:
              number: {{ .Values.service.port }}