image:
  repository: asia-southeast1-docker.pkg.dev/optimexdev/backend-images/backend
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

resources: {}

autoscaling:
  enabled: false

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  pollingInterval: 10
  cooldownPeriod: 60
  threshold: "5"

  prometheus:
    serverAddress: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
    query: |
      sum(
        rate(istio_requests_total{
          reporter="destination",
          destination_service="{{ include "backend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        }[1m])
      )

istio:
  enabled: true
  host: "demo-ravid-cloud.duckdns.org"
  gatewaySelector:
    app: "istio-ingress"
    istio: "ingress"

monitoring:
  enabled: true
  namespace: monitoring

  prometheus:
    releaseLabelKey: release
    releaseName: monitoring

  # ---- istiod (control-plane) ----
  istiod:
    enabled: true
    namespace: istio-system
    service:
      selectorLabels:
        app: istiod
      portName: http-monitoring   # 15014
      path: /metrics
      interval: 30s

  # ---- envoy sidecars (data-plane) ----
  sidecars:
    enabled: true
    anyNamespace: true
    namespaces: ["default"]
    portName: http-envoy-prom     # 15090
    path: /stats/prometheus
    interval: 30s
    requireIstioSidecar: true

  # ---- ingress gateway ---- 
  ingressGateway:
    enabled: false
    namespace: istio-system
    service:
      selectorLabels:
        istio: ingressgateway
      portName: http-envoy-prom   # 15090
      path: /stats/prometheus
      interval: 30s
