image:
  repository: ghcr.io/OWNER/REPO
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

resources: {}

# HPA default following CPU
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

# Scale follow up request/s through KEDA + Prometheus
keda:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  pollingInterval: 15
  cooldownPeriod: 60
  prometheus:
    serverAddress: http://prometheus-server.prometheus.svc.cluster.local
    metricName: requests_per_second
    threshold: "10"  # scale up if >10 req/s
    query: |
      sum(rate(istio_requests_total{reporter="destination",destination_workload="{{ include "backend.fullname" . }}"}[1m]))

istio:
  enabled: true
  host: "demo-ravid-cloud.duckdns.org"
  