name: ci-cd

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'charts/**'
      - '.github/workflows/ci-cd.yml'
  workflow_dispatch: {}

env:
  AR_REGION: ${{ secrets.AR_REGION }}
  AR_REPO:   ${{ secrets.AR_REPO }}
  IMAGE_NAME: backend
  IMAGE_TAG: sha-${{ github.sha }}

  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: github-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin & kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin kubectl --quiet

      - name: Configure Docker to Artifact Registry
        run: |
          gcloud auth configure-docker "${AR_REGION}-docker.pkg.dev" --quiet

      - name: Build & Push image
        uses: docker/build-push-action@v6
        env:
          IMAGE_REPO: ${{ env.AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

      - name: Get cluster creds
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$GCP_PROJECT_ID"
        env:
          GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
          GKE_ZONE: ${{ secrets.GKE_ZONE }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        env:
          IMAGE_REPO: ${{ env.AR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}
        run: |
          helm upgrade --install backend ./charts/backend \
            --namespace ${K8S_NAMESPACE} --create-namespace \
            --set image.repository=${IMAGE_REPO} \
            --set image.tag=${IMAGE_TAG}
