name: ci-cd

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'charts/**'
      - '.github/workflows/ci-cd.yml'
  workflow_dispatch: {}

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}
  IMAGE_TAG: sha-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # push GHCR
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin & kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin kubectl --quiet

      - name: Get cluster creds
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$GCP_PROJECT_ID"
        env:
          GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
          GKE_ZONE: ${{ secrets.GKE_ZONE }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install backend ./charts/backend \
            --namespace default --create-namespace \
            --set image.repository=${IMAGE_REPO} \
            --set image.tag=${IMAGE_TAG}